package indexadormp3;

import indexadormp3.Gestion;
import indexadormp3.Mp3;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author spair
 */
public class archivoGUI extends javax.swing.JFrame {

    /**
     * Creamos dos ArrayList<Mp3>
     * El primero será para todas las canciones de la BD
     * El segundo será para las canciones que seleccionemos en la interfaz
     */
    public ArrayList<Mp3> canciones;
    public ArrayList<Mp3> cancionesSeleccionadas = new ArrayList<Mp3>();
    
    /**
     * Creamos un objeto Gestión
     */
    Gestion g = new Gestion();
    
    /**
     * Creamos los modelos para los JList
     * model1 será para jl1
     * model2 será para jl2
     */
    public DefaultListModel<String> model1 = new DefaultListModel<>();
    public DefaultListModel<String> model2 = new DefaultListModel<>();

    /**
     * Creates new form archivoGUI
     */
    public archivoGUI() {
        initComponents();
        
        /**
         * Al iniciar jfc no será visible
         */
        this.jfc.setVisible(false);
        
        /**
         * Rellenamos canciones con los datos de la BD
         */
        canciones = g.listarCanciones();
        
        /**
         * Rellenamos jl1
         */
        rellenarLista(canciones);
    }

    /**
     * Este método sirve para rellenar el JList jl1
     * @param list: aquí le pasamos la lista de las canciones que queremos introducir en jl1
     */
    public void rellenarLista(ArrayList<Mp3> list) {
        
        /**
         * Recorremos la lista de las canciones
         */
        for (int i = 0; i < list.size(); i++) {
            
            /**
             * Y añadimos al modelo los elementos
             * Quedará como: 
             * Nombre Canción - Nombre Artista
             */
            model1.addElement(list.get(i).getNombre() + " - " + list.get(i).getArtista());
        }
        jl1.setModel(model1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jfc = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jtfNombrePL = new javax.swing.JTextField();
        jbtGenerador = new javax.swing.JButton();
        jtfRuta = new javax.swing.JTextField();
        jbtAnnadirCancion = new javax.swing.JButton();
        jtfBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtCarpeta1 = new javax.swing.JButton();
        jbtCarpeta2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jfc, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jfc, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 86, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jtfNombrePL.setName("Nombre Playlist"); // NOI18N

        jbtGenerador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtGenerador.setText("Generar");
        jbtGenerador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtGeneradorMouseClicked(evt);
            }
        });
        jbtGenerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGeneradorActionPerformed(evt);
            }
        });

        jtfRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRutaActionPerformed(evt);
            }
        });

        jbtAnnadirCancion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtAnnadirCancion.setText("Añadir");
        jbtAnnadirCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAnnadirCancionMouseClicked(evt);
            }
        });

        jtfBuscador.setName("Ruta"); // NOI18N

        jLabel1.setText("Generar M3U");

        jLabel2.setText("Añadir canciones");

        jLabel3.setText("Nombre de Playlist");

        jbtCarpeta1.setText("Carpeta");
        jbtCarpeta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtCarpeta1MouseClicked(evt);
            }
        });

        jbtCarpeta2.setText("Carpeta");
        jbtCarpeta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtCarpeta2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtCarpeta1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbtGenerador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(jtfNombrePL, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1)
                    .addComponent(jbtAnnadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtCarpeta2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCarpeta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jtfNombrePL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtGenerador, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCarpeta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtAnnadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jl1.setModel(model1);
        jl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jl2.setModel(model2);
        jl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtGeneradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGeneradorActionPerformed


    }//GEN-LAST:event_jbtGeneradorActionPerformed

    private void jtfRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRutaActionPerformed
        
    }//GEN-LAST:event_jtfRutaActionPerformed

    /**
     * Con este botón añadiremos canciones a la BD
     * @param evt 
     */
    private void jbtAnnadirCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAnnadirCancionMouseClicked
        
        /**
         * Llamamos al método annadirCancion de Gestión
         */
        g.annadirCancion(jtfRuta.getText());
        
        /**
         * Actualizamos jl1
         */
        canciones = g.listarCanciones();
        rellenarLista(canciones);
    }//GEN-LAST:event_jbtAnnadirCancionMouseClicked

    private void jl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl1MouseClicked
        
        /**
         * En selección guardaremos el valor del elemento de la lista que hayamos seleccionado
         * Y se guardarán en un array de tipo String
         * Se ha elegido un array normal porque se puede utilizar el método split()
         */
        String seleccion = jl1.getSelectedValue();
        String[] array = seleccion.split(" - ");
        
        /**
         * Añadimos a canciones seleccionadas el nombre y el nombre del artista por separado
         */
        cancionesSeleccionadas.add(g.buscarCancion(array[0], array[1]));

        /**
         * Se borra el elemento de jl1
         * Se añade el elemento a jl2
         */
        model1.removeElement(seleccion);
        model2.addElement(seleccion);
    }//GEN-LAST:event_jl1MouseClicked

    private void jl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl2MouseClicked
        
        /**
         * Este método funciona igual que el anterior pero borrando de jl2 y añadiendo a jl1
         * Además en vez de añadir a cancionesSeleccionadas se borrará la canción que hayamos seleccionado
         */
        String seleccion = jl2.getSelectedValue();
        String[] array = seleccion.split(" - ");
        int indice = jl2.getSelectedIndex();
        
        cancionesSeleccionadas.remove(indice); 
        
        model2.removeElement(seleccion);
        model1.addElement(seleccion);
    }//GEN-LAST:event_jl2MouseClicked

    private void jbtGeneradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtGeneradorMouseClicked
        
        /**
         * Este método llamarña al método m3u de Gestión para generar el archivo M3U
         */
        g.m3u(jtfBuscador.getText(), jtfNombrePL.getText(), cancionesSeleccionadas);
    }//GEN-LAST:event_jbtGeneradorMouseClicked

    private void jbtCarpeta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCarpeta1MouseClicked
        
        /**
         * Hace que jfc sea visible
         * Y que en jfc se puedan seleccionar archivos y directorios
         */
        this.jfc.setVisible(true);
        this.jfc.setFileSelectionMode(jfc.FILES_AND_DIRECTORIES);
        
        int result = this.jfc.showOpenDialog(this);

        /**
         * Si no se ha cancelado la busqueda...
         */
        if (result != jfc.CANCEL_OPTION) {

            /**
             * ...creamos un objeto de tipo File
             * Y recoge la ruta del archivo o directorio seleccionado
             */
            File fileName = this.jfc.getSelectedFile();

            /**
             * Si la ruta es nula o está vacía...
             */
            if ((fileName == null) || (fileName.getName().equals(""))) {
                
                /**
                 * ..se muestra en el buscador lo siguiente
                 */
                this.jtfBuscador.setText("...");
            } else { //Sino...
                
                /**
                 * Se mostrará en el buscador la ruta del archivo o directorio
                 */
                this.jtfBuscador.setText(fileName.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_jbtCarpeta1MouseClicked

    private void jbtCarpeta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCarpeta2MouseClicked
        
        /**
         * Este método funciona igual que el anterior
         * Pero aquí filtraremos los archivos que termine en Mp3 o mp3
         */
        this.jfc.setVisible(true);
        this.jfc.setFileSelectionMode(jfc.FILES_AND_DIRECTORIES);

        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("Mp3", "mp3");
        this.jfc.setFileFilter(imgFilter);
        int result = this.jfc.showOpenDialog(this);

        if (result != jfc.CANCEL_OPTION) {

            File fileName = this.jfc.getSelectedFile();

            if ((fileName == null) || (fileName.getName().equals(""))) {
                this.jtfRuta.setText("...");
            } else {
                this.jtfRuta.setText(fileName.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_jbtCarpeta2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(archivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(archivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(archivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(archivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new archivoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtAnnadirCancion;
    private javax.swing.JButton jbtCarpeta1;
    private javax.swing.JButton jbtCarpeta2;
    private javax.swing.JButton jbtGenerador;
    private javax.swing.JFileChooser jfc;
    private javax.swing.JList<String> jl1;
    private javax.swing.JList<String> jl2;
    private javax.swing.JTextField jtfBuscador;
    private javax.swing.JTextField jtfNombrePL;
    private javax.swing.JTextField jtfRuta;
    // End of variables declaration//GEN-END:variables
}
