package indexadormp3;
// Generated 09-feb-2021 16:18:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mp3 generated by hbm2java
 */
public class Mp3 implements java.io.Serializable {
    
    /**
     * Creamos las propiedades de la clase Mp3
     */
    private int idMp3;
    private String nombre;
    private String album;
    private String artista;
    private Date duracion;
    private String estilo;
    private String anno;
    private String ruta;

    /**
     * Creamos sus constructores
     */
    public Mp3() {
    }

    public Mp3(String nombre, String album, String artista, Date duracion, String estilo, String anno, String ruta) {
       this.nombre = nombre;
       this.album = album;
       this.artista = artista;
       this.duracion = duracion;
       this.estilo = estilo;
       this.anno = anno;
       this.ruta = ruta;
    }
    
    public Mp3(String nombre, String album, String artista, Date duracion, String estilo, String ruta) {
       this.nombre = nombre;
       this.album = album;
       this.artista = artista;
       this.duracion = duracion;
       this.estilo = estilo;
       this.ruta = ruta;
    }
   
    /**
     * Creamos los getters y los setters
     * @return 
     */
    public int getIdMp3() {
        return this.idMp3;
    }
    
    public void setIdMp3(int idMp3) {
        this.idMp3 = idMp3;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAlbum() {
        return this.album;
    }
    
    public void setAlbum(String album) {
        this.album = album;
    }
    public String getArtista() {
        return this.artista;
    }
    
    public void setArtista(String artista) {
        this.artista = artista;
    }
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }
    public String getEstilo() {
        return this.estilo;
    }
    
    public void setEstilo(String estilo) {
        this.estilo = estilo;
    }
    public String getAnno() {
        return this.anno;
    }
    
    public void setAnno(String anno) {
        this.anno = anno;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
}


