/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajadetextopersonalizada;

import java.awt.Color;
import java.awt.Font;
import java.awt.KeyEventDispatcher;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.TextEvent;
import java.awt.event.TextListener;
import javax.swing.JTextField;

/**
 *
 * @author spair
 */
public class txf extends JTextField implements MouseListener, KeyListener {
    //Saved Colors and enable redcolouring method 
    private Color colortxNormal = new Color(180, 180, 180);
    private Color colortxNormal2 = new Color(255, 255, 255);
    private Color textcolornegative = new Color(255, 0, 0);
    private boolean habilitarnumerosrojos = true;


        
    //Create JTextField
    public void txf() {
        JTextField tx = new JTextField("Custom TextField");
    }

    /**
     * Creates new form txf Set text to its initial value "Introduzca un numero"
     * Same with color. And adds the proper listeners , Mouse and Key.
     */
    public txf() {
        try{
        initComponents();
        this.setText("Introduzca un numero");
        this.setBackground(colortxNormal);
        this.addMouseListener(this);
        this.addKeyListener(this);
        }catch(Exception ex){
            System.out.println("Algo fue mal");
        }
    }

    /**
     * Disables or enables red numbers, can be changed in Netbeans GUI.
     *
     * @return
     */
    public boolean isHabilitarnumerosrojos() {
        return habilitarnumerosrojos;
    }

    public void setHabilitarnumerosrojos(boolean habilitarnumerosrojos) {
        this.habilitarnumerosrojos = habilitarnumerosrojos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When you click the textfield for the first time this method changes its
     * colour and deletes its text
     *
     * @param e
     */
    @Override
    public void mousePressed(MouseEvent e) {
        try {
            this.setBackground(colortxNormal2);
            this.setText("");
        } catch (Exception ex) {
            System.out.println("Algo fue mal");
        }
    }

    /**
     * When you press any key this method is called. Int key stores the key
     * pressed the first "if" is for disabling or enabling this method which
     * changes the color text from black to red if we get a negative number But
     * the method checks if the text starts with -, and then changes color to
     * red if that is true, if not it will stay black.
     *
     * @param e
     */
    @Override
    public void keyPressed(KeyEvent e) {
        try {
            int key = e.getKeyCode();
            if (habilitarnumerosrojos = true) {
                if (this.getText().startsWith("-")) {
                    this.setForeground(Color.red);
                } else {
                    this.setForeground(Color.black);
                }
            }
        } catch (Exception ex) {
            System.out.println("Ha habido un problema");
        }
    }

    // Those methods are not used.
    @Override
    public void mouseClicked(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyTyped(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
